import random
from pathlib import Path
import os

TARGET_ROOT_FOLDER = 'test/test_file_systems/004'
INITIAL_ITEMS_TO_CREATE_PER_DIR = 10
file_counter = 0 

p_decrement_quota = 0.05
p_item_is_dir = 0.2
n = INITIAL_ITEMS_TO_CREATE_PER_DIR
folders_to_populate = [Path(TARGET_ROOT_FOLDER)]

# `names` is generated by AI because the generating random names by myself seemed pointless.
names = [
    "Project_Plan",
    "Budget_2024",
    "Notes",
    "Photos",
    "Family_Vacation_2023",
    "Marketing_Strategy",
    "Meeting_Agenda_05182024",
    "Invoices",
    "Logo_Design",
    "Resume_JaneDoe",
    "John_Smith_CV",
    "Presentation",
    "Recipes",
    "Workouts",
    "Travel_Itinerary",
    "Code",
    "main",
    "App_Prototype",
    "User_Guide",
    "Database_Backup",
    "Emily_Johnson_Research",
    "Vacation_Planning",
    "Home_Renovation",
    "Finance_Report",
    "Marketing_Campaign_Results",
    "Photoshoot",
    "Landscape_Pics",
    "Scripts",
    "Data_Analysis",
    "Mary_Brown_Thesis",
    "Book_List",
    "Client_List",
    "Project_Alpha",
    "Design_Mockups",
    "Annual_Report",
    "Training_Materials",
    "Alex_Williams_Proposal",
    "Music",
    "Playlist",
    "Game_Dev",
    "Inventory_2024",
    "Meeting_Minutes",
    "Sara_Davis_Notes",
    "House_Hunting",
    "Recipes_Vegan",
    "Daily_Journal",
    "My_Blog",
    "Travel_Bucket_List",
    "Budget_Analysis",
    "Fitness_Tracker",
    "Olivia_Martin_Resume",
    "Sales_Report",
    "Jake_Parker_Project",
    "Workshop_Presentation",
    "Wedding_Plans",
    "Gift_Ideas",
    "Vacation_Photos",
    "Eric_Thompson_Budget",
    "Web_Development",
    "client_feedback",
    "Performance_Review",
    "Painting_Projects",
    "Contracts",
    "Jenny_Lee_Research",
    "Event_Planning",
    "Task_List",
    "Personal_Finance",
    "Holiday_Cards",
    "Marketing_Assets",
    "Volunteer_Work",
    "Inventory_Management",
    "Daniel_Adams_Bio",
    "Startup_Pitch",
    "New_Home_Design",
    "Budget_Tracker",
    "Employee_Handbook",
    "Rachel_Taylor_Proposal",
    "Grocery_List",
    "Vacation_Schedule",
    "Workshop_Materials",
    "Freelance_Work",
    "Business_Plan",
    "Contact_List",
    "William_Clark_Resume",
    "Social_Media_Content",
    "Sarah_Kim_Project",
    "Legal_Documents",
    "App_Documentation",
    "Home_Inventory",
    "Marketing_Research",
    "Tech_Support",
    "Meeting_Notes",
    "Peter_Jones_Thesis",
    "Birthday_Party_Plans",
    "Retirement_Planning",
    "Product_Designs",
    "Sam_Harris_Proposal",
    "Feedback_Forms",
    "Office_Supplies",
    "Investment_Portfolio",
]

# `file content` is generated by AI because writing out lorem ipsum is not relevant to the assessment.
file_content = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer nec odio. Praesent libero. Sed cursus ante dapibus diam. Sed nisi. Nulla quis sem at nibh elementum imperdiet. Duis sagittis ipsum. Praesent mauris. Fusce nec tellus sed augue semper porta. Mauris massa. Vestibulum lacinia arcu eget nulla. 

Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Curabitur sodales ligula in libero. Sed dignissim lacinia nunc. Curabitur tortor. Pellentesque nibh. Aenean quam. In scelerisque sem at dolor. Maecenas mattis. Sed convallis tristique sem. Proin ut ligula vel nunc egestas porttitor. 

Morbi lectus risus, iaculis vel, suscipit quis, luctus non, massa. Fusce ac turpis quis ligula lacinia aliquet. Mauris ipsum. Nulla metus metus, ullamcorper vel, tincidunt sed, euismod in, nibh. Quisque volutpat condimentum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. 

Nam nec ante. Sed lacinia, urna non tincidunt mattis, tortor neque adipiscing diam, a cursus ipsum ante quis turpis. Nulla facilisi. Ut fringilla. Suspendisse potenti. Nunc feugiat mi a tellus consequat imperdiet. Vestibulum sapien. Proin quam. Etiam ultrices. 

Suspendisse in justo eu magna luctus suscipit. Sed lectus. Integer euismod lacus luctus magna. Quisque cursus, metus vitae pharetra auctor, sem massa mattis sem, at interdum magna augue eget diam. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Morbi lacinia molestie dui. Praesent blandit dolor. 

Sed non quam. In vel mi sit amet augue congue elementum. Morbi in ipsum sit amet pede facilisis laoreet. Donec lacus nunc, viverra nec, blandit vel, egestas et, augue. Vestibulum tincidunt malesuada tellus. Ut ultrices ultrices enim. Curabitur sit amet mauris. Morbi in dui quis est pulvinar ullamcorper. Nulla facilisi.
"""

def create_item(parent):
    if p_item_is_dir > random.random():
        create_dir(parent=parent)
    else:
        create_file(parent)

def create_file(parent):
    name = random.choice(names)

    this_file_content = file_content * random.randint(1, 10)

    new_file = Path(parent, name+".txt")
    if new_file.exists():
        create_file(parent)
        return

    with open(new_file, 'w') as fp:
        fp.write(this_file_content)


def create_dir(parent):
    new_dir_path = Path(parent, random.choice(names))
    if new_dir_path.exists():
        create_dir(parent)
        return
    new_dir_path.mkdir()
    folders_to_populate.append(new_dir_path)


def update_items_quota(n):
    if random.random() < p_decrement_quota:
        n-=1
    return n


def populate_dir(target_dir, n):
    n = update_items_quota(n)
    if n == 0:
        return
    for _ in range(n):
        create_item(target_dir)
    
    while folders_to_populate:
        empty_dir = folders_to_populate.pop()
        assert empty_dir.exists()
        populate_dir(empty_dir, n)
    

populate_dir(TARGET_ROOT_FOLDER, INITIAL_ITEMS_TO_CREATE_PER_DIR)

